# Type is laptop or openwrt
TYPE = laptop
# Package Version
VERSION = "1.0.13"

OBJS = main.o eloop.o indigo_api.o indigo_packet.o utils.o wpa_ctrl.o
CFLAGS += -g

ifeq ($(TYPE),laptop)
CC = gcc
CFLAGS += -D_LAPTOP_

else ifeq ($(TYPE),wts_openwrt)
CC = /openwrt/QCA_Sniffer_11ax/qsdk/staging_dir/toolchain-aarch64_cortex-a53_gcc-5.2.0_musl-1.1.16/bin/aarch64-openwrt-linux-gcc
LD = /openwrt/QCA_Sniffer_11ax/qsdk/staging_dir/toolchain-aarch64_cortex-a53_gcc-5.2.0_musl-1.1.16/bin/aarch64-openwrt-linux-ld
# _OPENWRT_: Use OPENWRT
CFLAGS += -D_OPENWRT_
# _WTS_OPENWRT_: WTS OPENWRT specific changes
CFLAGS += -D_WTS_OPENWRT_

else
# upstream OPENWRT
CC = /openwrt/QCA_Sniffer_11ax/qsdk/staging_dir/toolchain-arm_cortex-a7_gcc-5.2.0_musl-1.1.16_eabi/bin/arm-openwrt-linux-gcc
LD = /openwrt/QCA_Sniffer_11ax/qsdk/staging_dir/toolchain-arm_cortex-a7_gcc-5.2.0_musl-1.1.16_eabi/bin/arm-openwrt-linux-ld
# _OPENWRT_: Use OPENWRT
CFLAGS += -D_OPENWRT_
endif

# Define the app is for DUT or platform
DUT_CFLAGS += -D_DUT_ 
TP_CFLAGS += -DCONFIG_CTRL_IFACE_UDP
TP_CFLAGS += -D_TEST_PLATFORM_

CFLAGS += -D_DYNAMIC_DUT_TP_

# Define the package version
ifneq ($(VERSION),)
CFLAGS += -D_VERSION_='$(VERSION)'
endif

all: libdut.so libtest_platform.so app

%.o: %.c 
	$(CC) $(CFLAGS) -c -o $@ $<

app: $(OBJS)
	$(CC) $(CFLAGS) -rdynamic -o $@ $^ -ldl

indigo_api_callback_dut.o:indigo_api_callback_dut.c
	$(CC) $(CFLAGS) $(DUT_CFLAGS) -fPIC -c indigo_api_callback_dut.c -o indigo_api_callback_dut.o
vendor_specific_dut.o:vendor_specific_dut.c
	$(CC) $(CFLAGS) $(DUT_CFLAGS) -fPIC -c vendor_specific_dut.c -o vendor_specific_dut.o

libdut.so:indigo_api_callback_dut.o vendor_specific_dut.o
	$(CC) $(CFLAGS) $(DUT_CFLAGS) -shared -o libdut.so indigo_api_callback_dut.o vendor_specific_dut.o

indigo_api_callback_tp.o:indigo_api_callback_tp.c
	$(CC) $(CFLAGS) $(TP_CFLAGS) -fPIC -c indigo_api_callback_tp.c -o indigo_api_callback_tp.o
vendor_specific_tp.o:vendor_specific_tp.c
	$(CC) $(CFLAGS) $(TP_CFLAGS) -fPIC -c vendor_specific_tp.c -o vendor_specific_tp.o

libtest_platform.so:indigo_api_callback_tp.o vendor_specific_tp.o
	$(CC) $(CFLAGS) $(TP_CFLAGS) -shared -o libtest_platform.so indigo_api_callback_tp.o vendor_specific_tp.o

clean:
	rm -rf app *.o *.so
